# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151202175702 on 2016-02-08 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyeriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(default=0, upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
